clear all;clc
x0=[-1,1];%[-1,1],[1,-1];%初始点;
%采用缺省算法模式，无线性和上下界约束;
opt1=optimoptions(@fmincon,'MaxIterations',3000,...
                           'MaxFunctionEvaluations',20000);
[x1,fv1,ef1,out1,lag1,grad1,hess1]=fmincon(@exam0902fun,x0,...
    [],[],[],[],[],[],@exam0902con,opt1);
opt2=optimoptions(@fmincon,'MaxIterations',3000,...
                           'MaxFunctionEvaluations',20000,...
                           'SpecifyObjectiveGradient',true,...
                           'SpecifyConstraintGradient',true,...
                           'DerivativeCheck','on');
%采用缺省算法模式，无线性和上下界约束;
[x2,fv2,ef2,out2,lag2,grad2,hess2]=fmincon(@exam0902fun,x0,...
    [],[],[],[],[],[],@exam0902con,opt2);
[[x1,fv1,ef1]',[x2,fv2,ef2]'],out1,out2